language: python

cache: pip

dist: xenial  # required for python3.7

python:
    - "3.6"
    - "3.7"

install:
    - pip install .[dev]

script:
    - pytest
    - flake8 pychubby

after_success:
    - codecov
